#ifndef __TORCH_HPP__
#define __TORCH_HPP__

#pragma once

#define TORCH_NAME Torch
#define TORCH_VER_MAJOR 1
#define TORCH_VER_MINOR 1
#define TORCH_VER_RELEASE 0
#define TORCH_VER_STR KFL_STRINGIZE(KLAYGE_NAME) " " KFL_STRINGIZE(KLAYGE_VER_MAJOR) "." KFL_STRINGIZE(KLAYGE_VER_MINOR) "." KFL_STRINGIZE(KLAYGE_VER_RELEASE)

#endif